"""Adding default branch group

Revision ID: 018f920c63aa
Revises: 905469020a4a
Create Date: 2024-12-17 18:51:56.275487

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '018f920c63aa'
down_revision = '905469020a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
            CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
            INSERT INTO public.branchgroup (id, name)
            VALUES (uuid_generate_v4(), 'Основной');
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
