"""Added new column in branches

Revision ID: 0d91a6e072df
Revises: 55acd5cfd8d0
Create Date: 2024-12-13 18:32:07.331794

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '0d91a6e072df'
down_revision = '55acd5cfd8d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
            ALTER TABLE branch
            ADD COLUMN send_notification JSONB DEFAULT '{}';
        """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
            ALTER TABLE branch DROP COLUMN send_notification;
        """)
    # ### end Alembic commands ###
