"""Branch migration

Revision ID: 4c750f64a46c
Revises: 64899d2d2ea6
Create Date: 2024-12-08 16:48:00.858244

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4c750f64a46c'
down_revision = '64899d2d2ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
