"""Updated branches

Revision ID: 55acd5cfd8d0
Revises: 42df3a96c0d8
Create Date: 2024-12-13 18:31:33.569011

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '55acd5cfd8d0'
down_revision = '42df3a96c0d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('work_hours', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('branch', sa.Column('responsible_user_for_authomative_actions', sa.Uuid(), nullable=True))
    op.add_column('branch', sa.Column('display_color', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.create_foreign_key(None, 'branch', 'user', ['responsible_user_for_authomative_actions'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'branch', type_='foreignkey')
    op.drop_column('branch', 'display_color')
    op.drop_column('branch', 'responsible_user_for_authomative_actions')
    op.drop_column('branch', 'work_hours')
    # ### end Alembic commands ###
