"""Updated user table

Revision ID: 68f271ffd9c5
Revises: cdc403441f62
Create Date: 2024-12-17 16:11:31.398505

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68f271ffd9c5'
down_revision = 'cdc403441f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
            ALTER TABLE public.user    
                ADD short_description VARCHAR(200) DEFAULT NULL,
                ADD main_description VARCHAR DEFAULT NULL,
                ADD phone VARCHAR(20) NOT NULL DEFAULT '+77777777777',
                ADD lang VARCHAR(20) DEFAULT 'kz',
                ADD branch UUID DEFAULT NULL,
                ADD CONSTRAINT fk_branch
                FOREIGN KEY (branch) REFERENCES public.branch (id)
                ON DELETE CASCADE,
                ADD job_role UUID DEFAULT NULL,
                ADD allow_authorization BOOLEAN DEFAULT TRUE,
                ADD notification BOOLEAN DEFAULT TRUE,
                ADD support_contact VARCHAR(100) DEFAULT NULL,
                ADD role_type VARCHAR(100) DEFAULT 'staff',
                ADD start_date TIMESTAMP DEFAULT current_timestamp,
                ADD end_date TIMESTAMP DEFAULT NULL,
                ADD birth_date TIMESTAMP DEFAULT NULL,
                ADD iin VARCHAR(12) DEFAULT NULL,
                ADD passport_data VARCHAR(50) DEFAULT NULL,
                ADD address VARCHAR(100) DEFAULT NULL,
                ADD district VARCHAR(50) DEFAULT NULL,
                ADD profile_image VARCHAR(255) DEFAULT NULL;
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
            ALTER TABLE public.user    
                DROP COLUMN short_description,
                DROP COLUMN main_description,
                DROP COLUMN phone,
                DROP COLUMN lang,
                DROP COLUMN branch,
                DROP CONSTRAINT fk_branch,
                DROP COLUMN job_role,
                DROP COLUMN allow_authorization,
                DROP COLUMN notification,
                DROP COLUMN support_contact,
                DROP COLUMN role_type,
                DROP COLUMN start_date,
                DROP COLUMN end_date,
                DROP COLUMN birth_date,
                DROP COLUMN iin,
                DROP COLUMN passport_data,
                DROP COLUMN address,
                DROP COLUMN district,
                DROP COLUMN profile_image;
        """
    )
    # ### end Alembic commands ###
