"""Updating branch field

Revision ID: 8516ca36a195
Revises: b9dcd885d897
Create Date: 2025-01-05 20:22:19.267479

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8516ca36a195'
down_revision = 'b9dcd885d897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
            ALTER TABLE public.branch
            ALTER COLUMN display_color DROP NOT NULL;
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
