"""Branch migration

Revision ID: 8dea193661f1
Revises: 4c750f64a46c
Create Date: 2024-12-08 17:09:10.952568

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8dea193661f1'
down_revision = '4c750f64a46c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branchgroup',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branch',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('internal_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('abbreviation', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('newsletter_address', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('address_note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('time_zone', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('workdays', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('holidays', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['branchgroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('branch')
    op.drop_table('branchgroup')
    # ### end Alembic commands ###
