"""Adding default roles

Revision ID: 905469020a4a
Revises: 68f271ffd9c5
Create Date: 2024-12-17 17:34:30.588570

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '905469020a4a'
down_revision = '68f271ffd9c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
            CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
            CREATE TABLE public.role (
                id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
                name VARCHAR(255),
                account_add BOOLEAN DEFAULT TRUE,
                account_update BOOLEAN DEFAULT TRUE,
                account_delete BOOLEAN DEFAULT TRUE,
                lesson_add BOOLEAN DEFAULT TRUE,
                lesson_update BOOLEAN DEFAULT TRUE,
                lesson_delete BOOLEAN DEFAULT TRUE,
                branch_add BOOLEAN DEFAULT TRUE,
                branch_update BOOLEAN DEFAULT TRUE,
                branch_delete BOOLEAN DEFAULT TRUE
            );
        """
    )

    op.execute(
        """
            INSERT INTO public.role (name)
            VALUES ('Администратор');
        """
    )

    op.execute(
        """
            INSERT INTO public.role (name, branch_add, branch_delete, branch_update)
            VALUES ('Менеджер', False, False, False);
        """
    )

    op.execute(
        """
            INSERT INTO public.role (name, branch_add, branch_delete, branch_update, account_add, account_update, account_delete)
            VALUES ('Учитель', False, False, False, False, False, False);
        """
    )

    op.execute(
        """
            UPDATE public.user
            SET job_role = (
                SELECT id
                FROM public.role
                WHERE name = 'Администратор'
            )
            WHERE is_superuser = True;
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
            DROP TABLE public.role;
        """
    )
    # ### end Alembic commands ###
